(()=>{'use strict';const c=window.MMMI_INTERNAL_CONFIG||{},ok=!!(c.supabaseUrl&&c.supabaseAnonKey),s=ok?supabase.createClient(c.supabaseUrl,c.supabaseAnonKey):null,$=q=>document.querySelector(q),$$=q=>document.querySelectorAll(q);let p=null;const mail=id=>`${id.trim().toLowerCase()}@mmmi.internal`;function alert(el,msg,type='danger'){el.textContent=msg;el.className=`alert alert-${type}`}function hide(el){el.classList.add('d-none')}function loginView(){ $('#login').classList.remove('d-none');$('#app').classList.add('d-none')}function appView(){ $('#login').classList.add('d-none');$('#app').classList.remove('d-none')}
async function profile(user){const{data,error}=await s.from('profiles').select('id,username,full_name,role,active,created_at').eq('id',user.id).single();if(error||!data?.active)throw Error('활성화된 사용자 정보를 찾을 수 없습니다.');p=data;$('#user-id').textContent=data.username;$('#avatar').textContent=(data.full_name||data.username)[0].toUpperCase();$('#welcome').textContent=data.full_name||data.username;$('#admin-nav').classList.toggle('d-none',data.role!=='admin');appView();route()}
async function start(){if(!ok){alert($('#setup-alert'),'인증 서버 설정 전입니다. Supabase 연결 정보를 입력하면 로그인이 활성화됩니다.','warning');$('#login-form button').disabled=true;return}const{data}=await s.auth.getSession();if(data.session)try{await profile(data.session.user)}catch(e){await s.auth.signOut();alert($('#login-alert'),e.message)}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();hide($('#login-alert'));const b=e.submitter;b.disabled=true;const{data,error}=await s.auth.signInWithPassword({email:mail($('#login-id').value),password:$('#login-password').value});try{if(error)throw Error('ID 또는 비밀번호가 올바르지 않습니다.');await profile(data.user);e.target.reset()}catch(x){alert($('#login-alert'),x.message)}finally{b.disabled=false}});$('#logout').onclick=async()=>{await s.auth.signOut();p=null;loginView()};
function route(){if(!p)return;let v=location.hash.slice(1)||'dashboard';if(v==='users'&&p.role!=='admin')v='dashboard';$$('.page').forEach(x=>x.classList.toggle('d-none',x.dataset.view!==v));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===v));if(v==='users')users()}addEventListener('hashchange',route);
const cm=new bootstrap.Modal('#create-modal'),pm=new bootstrap.Modal('#password-modal');$('#create-open').onclick=()=>{$('#create-form').reset();hide($('#create-alert'));cm.show()};$('#password-open').onclick=()=>{$('#password-form').reset();hide($('#password-alert'));pm.show()};
async function users(){const b=$('#users-body');b.innerHTML='<tr><td colspan="5" class="text-muted">Loading…</td></tr>';const{data,error}=await s.from('profiles').select('username,full_name,role,active,created_at').order('username');if(error){b.innerHTML='<tr><td colspan="5" class="text-danger">사용자 목록을 불러오지 못했습니다.</td></tr>';return}b.replaceChildren(...data.map(u=>{const r=document.createElement('tr');[u.username,u.full_name,u.role,u.active?'Active':'Disabled',new Date(u.created_at).toLocaleDateString('ko-KR')].forEach(v=>{const d=document.createElement('td');d.textContent=v||'—';r.append(d)});return r}))}
$('#create-form').addEventListener('submit',async e=>{e.preventDefault();hide($('#create-alert'));const b=e.submitter;b.disabled=true;try{const{data}=await s.auth.getSession(),res=await fetch(`${c.supabaseUrl}/functions/v1/create-user`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({username:$('#new-id').value,fullName:$('#new-name').value,password:$('#new-pass').value,role:$('#new-role').value})}),out=await res.json();if(!res.ok)throw Error(out.error||'계정을 생성하지 못했습니다.');alert($('#app-alert'),`${out.username} 계정을 생성했습니다.`,'success');cm.hide();await users()}catch(x){alert($('#create-alert'),x.message)}finally{b.disabled=false}});
$('#password-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const{error}=await s.auth.updateUser({password:$('#new-password').value});if(error)alert($('#password-alert'),error.message);else{pm.hide();alert($('#app-alert'),'비밀번호를 변경했습니다.','success')}b.disabled=false});start()})();
